version: 2
jobs:
  build:
    working_directory: ~/liberty-spa
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key:  yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: xvfb-run -a yarn test --single-run --no-progress --browser=ChromeNoSandbox
      - run: xvfb-run -a yarn e2e --no-progress --config=protractor-ci.conf.js